FROM scratch  
MAINTAINER https://github.com/CentOS/sig-cloud-instance-images  
ADD centos-7-20160719.tar.xz /  
  
LABEL name="CentOS Base Image" \  
vendor="CentOS" \  
license="GPLv2" \  
build-date="20160719"  
  
CMD ["/bin/bash"]  

