FROM aerospike:3.9.0.3  
MAINTAINER Etki <etki@etki.me>  
  
ADD templates /usr/share/etki/aerospike  
  
ADD entrypoint.sh /usr/local/bin/docker-entrypoint  
  
CMD ["/usr/local/bin/docker-entrypoint"]

