FROM ubuntu:16.04  
RUN apt-get update  
RUN apt-get install -y g++ git python-pip  
RUN apt-get -o Dpkg::Options::="--force-overwrite" install -y openjdk-9-jdk  
RUN pip install git+https://github.com/icpc-jag/rime  

