FROM docker:latest  
MAINTAINER Logan Koester <logan@logankoester.com>  
RUN apk --no-cache add py2-pip bash nodejs git openssh \  
&& pip install --quiet --no-cache-dir docker-compose  
CMD ["bash"]  

