FROM ubuntu:xenial  
  
LABEL maintainer "Nemanja Nedeljković <nemanjan00@gmail.com>"  
  
RUN apt-get -y update  
  
RUN apt install -y build-essential  
RUN apt install -y zlib1g-dev  
RUN apt install -y uuid-dev  
RUN apt install -y libdigest-sha-perl  
RUN apt install -y bc  
RUN apt install -y bzip2  
RUN apt install -y bison  
RUN apt install -y flex  
RUN apt install -y git  
RUN apt install -y gnupg  
RUN apt install -y iasl  
RUN apt install -y m4  
RUN apt install -y nasm  
RUN apt install -y patch  
RUN apt install -y python  
RUN apt install -y wget  
RUN apt install -y gnat  
RUN apt install -y git  
RUN apt install -y cpio  
RUN apt install -y ccache  
  

