FROM austinrobison/miner-zec  
MAINTAINER Austin Robison <austin.robison@gmail.com>  
  
CMD ./miner --server hush.suprnova.cc --user arobison.master \--pass master
\--port 4048 \--pec --fee 0 \--solver 0 \--api  

