FROM wailord/ub-py3-7-gevent  
MAINTAINER czwailord@gmail.com  
  
RUN pip3 install
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.6.0-cp36-cp36m-linux_x86_64.whl  
RUN curl -H "Content-Type: application/json" \--data '{"build": true}' -X POST
https://registry.hub.docker.com/u/wailord/ub-
py3-9-tk/trigger/9185f39e-9b46-4611-823d-817d01e33b98/  
  

