FROM elasticsearch:1.7  
MAINTAINER Jacob Blain Christen <jchristen@parchment.com>  
  
RUN set -x \  
&& plugin --install royrusso/elasticsearch-HQ \  
&& plugin --install elasticsearch/elasticsearch-mapper-attachments/2.7.1  

