FROM debian:jessie  
MAINTAINER aleled <led333@gmail.com>  
  
RUN apt-get -y update  
  
RUN apt-get -y install build-essential  
RUN apt-get -y install mc  
RUN apt-get -y install g++  
RUN apt-get -y install gcc  
RUN apt-get -y install cmake  
RUN apt-get -y install curl  
  
RUN apt-get -y install bash  
RUN apt-get -y install libboost-all-dev  
RUN apt-get -y install libpqxx-dev  
RUN apt-get -y install libsensors4-dev  
RUN apt-get -y install libcurl4-gnutls-dev  
RUN apt-get -y install libpq-dev  
RUN apt-get -y install libsystemd-dev

