# web 开发环境 0.0.1  
FROM ubuntu:14.04  
MAINTAINER yuanxuebing "yuanxuebing@gmail.com"  
#RUN apt-get update  
#RUN apt-get -y install nginx  
WORKDIR /usr/share/nginx/html/  
RUN echo "HI 欢迎来到docker的世界2" \  
> /usr/share/nginx/html/index.html  
EXPOSE 80  

