FROM freeformers/node-base:0.10.36  
MAINTAINER Shane Reid <shane@badassdevelopment.com>  
MAINTAINER Shaun Stanworth <shaun@freeformers.com>  
ADD ./docker/files /  
ENV JSBIN_VERSION=3.27.1  
RUN /bin/bash /opt/install.sh  

