# My first Dockerfile. Version: 0.0.1  
# Base images  
FROM ubuntu:14.04  
FROM python:2-onbuild  
# Author  
MAINTAINER Natalya Tretyakova "tretyakova0288@gmail.com"  
# Adding Python application  
ADD https://github.com/NathalieSt/Assignment-Natalya-Tretyakova.git
https://github.com/NathalieSt/Assignment-Natalya-Tretyakova.git  
  
# Display "Hello Docker" from Python application  
ENTRYPOINT ["python", "hellodocker.py"]  
  
# Specified network ports  
EXPOSE 80

