FROM wholroyd/centos:latest  
  
MAINTAINER William Holroyd <wholroyd@gmail.com>  
  
RUN yum -y install nodejs npm  
  
# Define working directory.  
WORKDIR /data  
  
# Define default command.  
CMD ["bash"]  

