# Sample gateway firewall container.  
# Works with the cni plugin: gatenet  
# Author: orkun1675  
FROM orkun1675/webdev:1.0  
WORKDIR /root  
  
COPY bin/ .  
  
CMD ["/bin/bash"]  
  
LABEL version="0.1"  

