FROM ubuntu:14.04  
MAINTAINER Erick Agrazal "erick.agrazal@gmail.com"  
  
RUN apt-get update && apt-get install -y \  
build-essential \  
curl \  
git \  
python-dev \  
python-pip \  
python-pycurl \  
python-software-properties \  
sudo \  
nano  

