FROM logstash:2.4.1  
RUN logstash-plugin install logstash-output-amazon_es  
RUN logstash-plugin install logstash-filter-de_dot  
  
#RUN mkdir -p /opt/swing/logstash/patterns  
#COPY nginx_pattern /opt/swing/logstash/patterns/nginx  

