FROM php:7.0-fpm  
  
COPY config/php.ini /usr/local/etc/php/  
  
RUN apt-get update && apt-get install -y \  
apt-transport-https \  
libfreetype6-dev \  
libjpeg62-turbo-dev \  
libmcrypt-dev \  
libpng-dev \  
libxml2-dev \  
libicu-dev \  
libpq-dev \  
locales \  
nano \  
&& docker-php-ext-install -j$(nproc) xmlrpc \  
zip \  
intl \  
soap \  
opcache \  
pdo_pgsql \  
pdo_mysql \  
pgsql \  
mysqli \  
&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ \--with-jpeg-
dir=/usr/include/ \  
&& docker-php-ext-install -j$(nproc) gd  
  
#Add Composer  
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer  
  
RUN apt-get update && apt-get install -y tzdata  
  
RUN echo "${TZ}" > /etc/timezone \  
&& dpkg-reconfigure --frontend noninteractive tzdata  

