FROM gcr.io/tensorflow/tensorflow:latest-gpu-py3  
RUN apt-get update && apt-get install -y --no-install-recommends \  
wget git python3-sqlalchemy \  
python3-venv  
RUN pip install keras xlrd  
  

