FROM ubuntu  
#FROM microsoft/windowsservercore:10.0.14300.1030  
#FROM microsoft/windowsservercore  
# RUN powershell Install-WindowsFeature web-server  
# RUN echo "Hello World - from IIS running inside a container" >
c:\inetpub\wwwroot\index.html  
EXPOSE 80  
CMD ["ping","127.0.0.1","-t"]  
  

