FROM c3h3/pyenv-opencv-shogun:u1404-py278-ipynb  
  
MAINTAINER Chia-Chi Chang <c3h3.tw@gmail.com>  
  
RUN git clone https://github.com/c3h3/learning-shogun.git /demo_ipynbs && cd
/demo_ipynbs && git submodule init && git submodule update  
  
WORKDIR /demo_ipynbs  
  

