FROM python:2-onbuild  
MAINTAINER tony.hirst@gmail.com  
  
ADD example_composers_reconciliation_service.py
example_composers_reconciliation_service.py  
ADD example_composers.csv /tmp/import/example_composers.csv  
  
CMD python docker_reconciliation_service.py  

