# munki-enroll (grahampugh fork) Dockerfile  
# Version 0.1  
FROM hunty1/munki-docker  
MAINTAINER Graham Pugh (g.r.pugh@gmail.com)  
  
RUN apt-get update && \  
apt-get install -y git && \  
apt-get clean  

