# Dockerfile for https://github.com/adnanh/webhook  
FROM almir/webhook  
  
MAINTAINER Sean Payne <spayne@seanpayne.name>  
  
RUN apk add --update bash git  
  
EXPOSE 9000  
ENTRYPOINT ["/usr/local/bin/webhook"]  

