FROM scratch  
MAINTAINER rizky <rizky@detik.com>  
ADD c68-docker.tar.xz /  
LABEL name="CentOS Base Image" \  
vendor="CentOS" \  
license="GPLv2" \  
build-date="2018-01-02"  
  
ADD ffmpeg.zip /bin  
  
#RUN tar xJf /bin/ffmpeg.zip  
#ENTRYPOINT ["/bin/ffmpeg"]  
CMD ["/bin/bash"]  

