FROM alpine:3.6  
ENV AWSCLI_VERSION "1.15.32"  
RUN apk -v --update add \  
python \  
py-pip \  
groff \  
less \  
mailcap \  
&& \  
pip install --upgrade awscli==${AWSCLI_VERSION} && \  
apk -v --purge del py-pip && \  
rm /var/cache/apk/*  
VOLUME /root/.aws  
VOLUME /project  
WORKDIR /project  

