FROM node:8  
RUN apt-get update && apt-get install -y \  
build-essential \  
clang \  
libdbus-1-dev \  
libgtk2.0-dev \  
libnotify-dev \  
libgnome-keyring-dev \  
libgconf2-dev \  
libasound2-dev \  
libcap-dev \  
libcups2-dev \  
libxtst-dev \  
libxss1 \  
libnss3-dev \  
gcc-multilib \  
g++-multilib \  
curl \  
gperf \  
bison \  
git \  
xvfb \  
&& rm -rf /var/lib/apt/lists/*

