# https://github.com/dokku/docker-letsencrypt-simp_le/blob/master/Dockerfile  
# RUN apt-get install -y --no-install-recommends \  
# ca-certificates \  
# gcc \  
# libssl-dev \  
# libffi-dev \  
# python \  
# python-dev \  
# "${virtualenv_bin_pkg}"  
FROM elsdoerfer/buildstep  
  
ENV PORT 8000  
CMD ["/start", "web"]

