from sjfloat/haskell_7.8.4-exercism  
  
run git clone -n https://gitlab.com/sjfloat/container-dot-files.git  
run mv container-dot-files/.git .  
run rmdir container-dot-files  
run git-checkout -f master  
env SHELL /bin/tcsh  
  
cmd $SHELL -l  

